import { School } from "@/components/schools/columns";

export async function getSchools(): Promise<School[]> {
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000"}/api/schools`,
      {
        // Add cache options for better performance
        next: {
          revalidate: 3600, // Revalidate every hour
          tags: ["schools"],
        },
      },
    );

    if (!response.ok) {
      throw new Error(`Failed to fetch schools: ${response.status}`);
    }

    return response.json();
  } catch (error) {
    console.error("Error fetching schools:", error);
    // Return empty array as fallback
    return [];
  }
}

// Direct database/API call (bypassing the API route)
export async function getSchoolsDirect(): Promise<School[]> {
  try {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 100));

    // This would be your direct database call or external API call
    // Example with external API:
    // const response = await fetch('https://your-external-api.com/schools');
    // return response.json();

    // Example with database call:
    // const schools = await db.schools.findMany();
    // return schools;

    // For now, return the same data as the API route
    return [
      {
        id: "1",
        name: "University of Alabama School of Dentistry",
        city: "Birmingham",
        state: "Alabama",
        programs: ["Orthodontics", "Pediatric Dentistry", "Periodontics", "Prosthodontics"],
        status: ["Citizens & Residents", "Non-residents"],
        website: "https://www.uab.edu/dentistry/home/",
      },
      {
        id: "2",
        name: "Arizona School of Dentistry & Oral Health",
        city: "Mesa",
        state: "Arizona",
        programs: ["Dental Public Health"],
        status: ["Non-residents"],
        website: "https://www.atsu.edu/arizona-school-of-dentistry-and-oral-health",
      },
      {
        id: "3",
        name: "Herman Ostrow School of Dentistry of USC",
        city: "Los Angeles",
        state: "California",
        programs: [
          "Endodontics",
          "Geriatric Dentistry",
          "Operative Dentistry",
          "Pediatric Dentistry",
          "Periodontics",
        ],
        status: ["Non-residents"],
        website: "https://dentistry.usc.edu/",
      },
      {
        id: "4",
        name: "Loma Linda University School of Dentistry",
        city: "Loma Linda",
        state: "California",
        programs: ["Endodontics", "Pediatric Dentistry", "Periodontics"],
        status: ["Non-residents"],
        website: "https://dentistry.llu.edu/",
      },
      {
        id: "5",
        name: "University of California, Los Angeles School of Dentistry",
        city: "Los Angeles",
        state: "California",
        programs: [],
        status: ["Non-residents"],
        website: "https://dentistry.ucla.edu/",
      },
      {
        id: "6",
        name: "University of California, San Francisco School of Dentistry",
        city: "San Francisco",
        state: "California",
        programs: ["Orthodontics", "Pediatric Dentistry", "Periodontics", "Prosthodontics"],
        status: ["Non-residents"],
        website: "https://dentistry.ucsf.edu/",
      },
      {
        id: "7",
        name: "University of the Pacific Arthur A. Dugoni School of Dentistry",
        city: "San Francisco",
        state: "California",
        programs: ["Orthodontics"],
        status: ["Non-residents"],
        website: "https://dental.pacific.edu/dental",
      },
      {
        id: "8",
        name: "University of Colorado School of Dental Medicine",
        city: "Aurora",
        state: "Colorado",
        programs: [],
        status: ["Non-residents"],
        website: "https://dental.cuanschutz.edu/",
      },
      {
        id: "9",
        name: "University of Connecticut School of Dental Medicine",
        city: "Farmington",
        state: "Connecticut",
        programs: [
          "AEGD programs for international dentists",
          "Oral and Maxillofacial Radiology",
          "Orthodontics",
          "Pediatric Dentistry",
          "Prosthodontics",
        ],
        status: ["Non-residents"],
        website: "https://dentalmedicine.uconn.edu/",
      },
      {
        id: "10",
        name: "Howard University College of Dentistry",
        city: "Washington",
        state: "District of Columbia",
        programs: ["GPR"],
        status: ["Non-residents"],
        website: "http://healthsciences.howard.edu/education/colleges/dentistry",
      },
      {
        id: "11",
        name: "Nova Southeastern University College of Dental Medicine",
        city: "Ft. Lauderdale",
        state: "Florida",
        programs: [
          "AEGD programs for international dentists",
          "Orthodontics",
          "Pediatric Dentistry",
          "Periodontics",
          "Prosthodontics",
        ],
        status: ["Non-residents"],
        website: "https://dental.nova.edu/",
      },
      {
        id: "12",
        name: "University of Florida College of Dentistry",
        city: "Gainesville",
        state: "Florida",
        programs: ["Oral and Maxillofacial Pathology"],
        status: ["Citizens & Residents", "Non-residents"],
        website: "https://dental.ufl.edu/",
      },
      {
        id: "13",
        name: "The Dental College of Georgia at Augusta University",
        city: "Augusta",
        state: "Georgia",
        programs: ["Endodontics"],
        status: ["Non-residents"],
        website: "https://www.augusta.edu/dentalmedicine/",
      },
      {
        id: "14",
        name: "University of Illinois at Chicago College of Dentistry",
        city: "Chicago",
        state: "Illinois",
        programs: ["Endodontics", "Prosthodontics"],
        status: ["Citizens & Residents", "Non-residents"],
        website: "http://dentistry.uic.edu/",
      },
      {
        id: "15",
        name: "Southern Illinois University School of Dental Medicine",
        city: "Alton",
        state: "Illinois",
        programs: [],
        status: ["Non-residents"],
        website: "https://www.siue.edu/dental/",
      },
      {
        id: "16",
        name: "Midwestern University College of Dental Medicine",
        city: "Indianapolis",
        state: "Indiana",
        programs: ["Endodontics", "Orthodontics", "Prosthodontics"],
        status: ["Non-residents"],
        website: "https://dentistry.iu.edu/",
      },
      {
        id: "17",
        name: "The University of Iowa College of Dentistry and Dental Clinics",
        city: "Iowa City",
        state: "Iowa",
        programs: ["Oral and Maxillofacial Radiology"],
        status: ["Non-residents"],
        website: "https://dentistry.uiowa.edu/",
      },
      {
        id: "18",
        name: "University of Kentucky College of Dentistry",
        city: "Lexington",
        state: "Kentucky",
        programs: ["Orthodontics"],
        status: ["Non-residents"],
        website: "https://dentistry.uky.edu/",
      },
      {
        id: "19",
        name: "University of Louisville School of Dentistry",
        city: "Louisville",
        state: "Kentucky",
        programs: ["Endodontics", "Orthodontics", "Periodontics", "Prosthodontics"],
        status: ["Non-residents"],
        website: "https://louisville.edu/dentistry/",
      },
      {
        id: "20",
        name: "Louisiana State University Health Science Center School of Dentistry",
        city: "New Orleans",
        state: "Louisiana",
        programs: [
          "Endodontics",
          "Orthodontics",
          "Pediatric Dentistry",
          "Periodontics",
          "Prosthodontics",
        ],
        status: ["Non-residents"],
        website: "https://www.lsusd.lsuhsc.edu/",
      },
      {
        id: "21",
        name: "University of Maryland School of Dentistry",
        city: "Baltimore",
        state: "Maryland",
        programs: [
          "AEGD programs for international dentists",
          "Endodontics",
          "Oral and Maxillofacial Surgery",
          "Orthodontics",
          "Pediatric Dentistry",
          "Prosthodontics",
        ],
        status: ["Non-residents"],
        website: "https://www.dental.umaryland.edu/",
      },
      {
        id: "22",
        name: "Boston University Henry M. Goldman School of Dental Medicine",
        city: "Boston",
        state: "Massachusetts",
        programs: [
          "AEGD programs for international dentists",
          "Dental Public Health",
          "Endodontics",
          "Operative Dentistry",
          "Oral and Maxillofacial Surgery",
          "Orthodontics",
          "Pediatric Dentistry",
          "Periodontics",
          "Prosthodontics",
        ],
        status: ["Non-residents"],
        website: "https://www.bu.edu/dental/",
      },
      {
        id: "23",
        name: "Harvard University School of Dental Medicine",
        city: "Boston",
        state: "Massachusetts",
        programs: [
          "Dental Public Health",
          "Endodontics",
          "Geriatric Dentistry",
          "Implantology",
          "Oral Medicine",
          "Oral and Maxillofacial Pathology",
          "Orthodontics",
          "Prosthodontics",
        ],
        status: ["Non-residents"],
        website: "https://hsdm.harvard.edu/",
      },
      {
        id: "24",
        name: "Tufts University School of Dental Medicine",
        city: "Boston",
        state: "Massachusetts",
        programs: [
          "Endodontics",
          "GPR",
          "Oral and Maxillofacial Surgery",
          "Orthodontics",
          "Pediatric Dentistry",
          "Periodontics",
          "Prosthodontics",
        ],
        status: ["Citizens & Residents", "Non-residents"],
        website: "https://dental.tufts.edu/",
      },
      {
        id: "25",
        name: "University of Detroit Mercy School of Dentistry",
        city: "Detroit",
        state: "Michigan",
        programs: ["Orthodontics"],
        status: ["Non-residents"],
        website: "https://dental.udmercy.edu/",
      },
      {
        id: "26",
        name: "University of Michigan School of Dentistry",
        city: "Ann Arbor",
        state: "Michigan",
        programs: ["Orthodontics"],
        status: ["Non-residents"],
        website: "https://dent.umich.edu/",
      },
      {
        id: "27",
        name: "University of Mississippi Medical Center School of Dentistry",
        city: "Jackson",
        state: "Mississippi",
        programs: ["Oral and Maxillofacial Surgery"],
        status: ["Non-residents"],
        website: "https://www.umc.edu/sod/SOD_Home.html",
      },
      {
        id: "28",
        name: "University of Nebraska Medical Center College of Dentistry",
        city: "Lincoln",
        state: "Nebraska",
        programs: ["Orthodontics"],
        status: ["Non-residents"],
        website: "https://www.unmc.edu/dentistry/",
      },
      {
        id: "29",
        name: "Rutgers School of Dental Medicine",
        city: "Newark",
        state: "New Jersey",
        programs: ["Orthodontics", "Pediatric Dentistry"],
        status: ["Non-residents"],
        website: "https://sdm.rutgers.edu/",
      },
      {
        id: "30",
        name: "New York University College of Dentistry",
        city: "New York",
        state: "New York",
        programs: ["Endodontics", "Orthodontics", "Prosthodontics"],
        status: ["Citizens & Residents", "Non-residents"],
        website: "https://dental.nyu.edu/",
      },
      {
        id: "31",
        name: "Stony Brook University School of Dental Medicine",
        city: "Stony Brook",
        state: "New York",
        programs: ["Periodontics"],
        status: ["Non-residents"],
        website: "https://dentistry.stonybrookmedicine.edu/",
      },
      {
        id: "32",
        name: "University at Buffalo School of Dental Medicine",
        city: "Buffalo",
        state: "New York",
        programs: [],
        status: ["Non-residents"],
        website: "http://dental.buffalo.edu/",
      },
      {
        id: "33",
        name: "Virginia Commonwealth University School of Dentistry",
        city: "Richmond",
        state: "Virginia",
        programs: [],
        status: ["Non-residents"],
        website: "https://dentistry.vcu.edu/programs/dds/",
      },
      {
        id: "34",
        name: "Ohio State University College of Dentistry",
        city: "Columbus",
        state: "Ohio",
        programs: ["Orthodontics"],
        status: ["Non-residents"],
        website: "https://dentistry.osu.edu/",
      },
      {
        id: "35",
        name: "University of Pittsburgh School of Dental Medicine",
        city: "Pittsburgh",
        state: "Pennsylvania",
        programs: ["Prosthodontics"],
        status: ["Non-residents"],
        website: "https://www.dental.pitt.edu/",
      },
      {
        id: "36",
        name: "Marquette University School of Dentistry",
        city: "Milwaukee",
        state: "Wisconsin",
        programs: ["Prosthodontics"],
        status: ["Non-residents"],
        website: "https://www.marquette.edu/dentistry/",
      },
      {
        id: "37",
        name: "University of Washington School of Dentistry",
        city: "Seattle",
        state: "Washington",
        programs: ["Oral and Maxillofacial Radiology", "Orthodontics", "Pediatric Dentistry"],
        status: ["Non-residents"],
        website: "https://www.dental.washington.edu/",
      },
      {
        id: "38",
        name: "University of Tennessee Health Science Center College of Dentistry",
        city: "Memphis",
        state: "Tennessee",
        programs: ["Prosthodontics"],
        status: ["Non-residents"],
        website: "https://www.uthsc.edu/dentistry/",
      },
      {
        id: "39",
        name: "University of Puerto Rico, School of Dental Medicine",
        city: "San Juan",
        state: "Puerto Rico",
        programs: ["Oral and Maxillofacial Surgery", "Orthodontics", "Pediatric Dentistry"],
        status: ["Non-residents"],
        website: "https://dental.rcm.upr.edu/",
      },
      {
        id: "40",
        name: "Texas A&M University College of Dentistry",
        city: "Dallas",
        state: "Texas",
        programs: [],
        status: [],
        website: "https://dentistry.tamu.edu/",
      },
      {
        id: "41",
        name: "Baylor College of Dentistry (Texas A&M University)",
        city: "Dallas",
        state: "Texas",
        programs: [],
        status: [],
        website: "https://dentistry.tamu.edu/",
      },
      {
        id: "42",
        name: "The University of Texas School of Dentistry at Houston",
        city: "Houston",
        state: "Texas",
        programs: [],
        status: [],
        website: "https://dentistry.uth.edu/",
      },
      {
        id: "43",
        name: "University of Texas Health Science Center at San Antonio School of Dentistry",
        city: "San Antonio",
        state: "Texas",
        programs: [],
        status: [],
        website: "https://www.uthscsa.edu/academics/dental",
      },
      {
        id: "44",
        name: "Roseman University of Health Sciences College of Dental Medicine",
        city: "South Jordan",
        state: "Utah",
        programs: [],
        status: [],
        website: "https://www.roseman.edu/academics/college-of-dental-medicine/",
      },
      {
        id: "45",
        name: "Medical University of South Carolina James B. Edwards College of Dental Medicine",
        city: "Charleston",
        state: "South Carolina",
        programs: [],
        status: [],
        website: "https://muschealth.org/medical-services/dentistry",
      },
      {
        id: "46",
        name: "Columbia University College of Dental Medicine",
        city: "New York",
        state: "New York",
        programs: [],
        status: [],
        website: "https://www.dental.columbia.edu/",
      },
      {
        id: "47",
        name: "University of Pennsylvania School of Dental Medicine",
        city: "Philadelphia",
        state: "Pennsylvania",
        programs: [],
        status: [],
        website: "https://www.dental.upenn.edu/",
      },
      {
        id: "48",
        name: "Temple University Maurice H. Kornberg School of Dentistry",
        city: "Philadelphia",
        state: "Pennsylvania",
        programs: [],
        status: [],
        website: "https://dentistry.temple.edu/",
      },
    ];
  } catch (error) {
    console.error("Error fetching schools directly:", error);
    return [];
  }
}
